services:

  redis-iam:
    image: redis:7.2.5-alpine3.20
    container_name: redis-iam

    env_file:
      - .env

    ports:
      - "${EXTERNAL_REDIS_PORT}:6379"

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped

    networks:
      - microservices-net

volumes:
  redis-iam-data:

networks:
  microservices-net:
    external: true