// Code generated for Tikhonov Nikita`s service
// © Tikhonov Nikita 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	context "golang.org/x/net/context"

	model "github.com/TikhonovNikita1996/Go-microservises-project/inventory/internal/model"
)

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: _a0, _a1
func (_m *InventoryService) GetPart(_a0 context.Context, _a1 string) (*model.Part, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Part, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Part); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type InventoryService_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *InventoryService_Expecter) GetPart(_a0 interface{}, _a1 interface{}) *InventoryService_GetPart_Call {
	return &InventoryService_GetPart_Call{Call: _e.mock.On("GetPart", _a0, _a1)}
}

func (_c *InventoryService_GetPart_Call) Run(run func(_a0 context.Context, _a1 string)) *InventoryService_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *InventoryService_GetPart_Call) Return(_a0 *model.Part, _a1 error) *InventoryService_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_GetPart_Call) RunAndReturn(run func(context.Context, string) (*model.Part, error)) *InventoryService_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// GetParts provides a mock function with given fields: _a0, _a1
func (_m *InventoryService) GetParts(_a0 context.Context, _a1 model.PartsFilter) ([]*model.Part, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]*model.Part, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []*model.Part); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InventoryService_GetParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParts'
type InventoryService_GetParts_Call struct {
	*mock.Call
}

// GetParts is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.PartsFilter
func (_e *InventoryService_Expecter) GetParts(_a0 interface{}, _a1 interface{}) *InventoryService_GetParts_Call {
	return &InventoryService_GetParts_Call{Call: _e.mock.On("GetParts", _a0, _a1)}
}

func (_c *InventoryService_GetParts_Call) Run(run func(_a0 context.Context, _a1 model.PartsFilter)) *InventoryService_GetParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.PartsFilter))
	})
	return _c
}

func (_c *InventoryService_GetParts_Call) Return(_a0 []*model.Part, _a1 error) *InventoryService_GetParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *InventoryService_GetParts_Call) RunAndReturn(run func(context.Context, model.PartsFilter) ([]*model.Part, error)) *InventoryService_GetParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
