// Code generated for Tikhonov Nikita`s service
// © Tikhonov Nikita 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	context "golang.org/x/net/context"

	model "github.com/TikhonovNikita1996/Go-microservises-project/order/internal/model"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CancelOrderByUuid provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) CancelOrderByUuid(ctx context.Context, uuid string) (model.CancelResponse, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByUuid")
	}

	var r0 model.CancelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CancelResponse, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CancelResponse); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.CancelResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CancelOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByUuid'
type OrderRepository_CancelOrderByUuid_Call struct {
	*mock.Call
}

// CancelOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) CancelOrderByUuid(ctx interface{}, uuid interface{}) *OrderRepository_CancelOrderByUuid_Call {
	return &OrderRepository_CancelOrderByUuid_Call{Call: _e.mock.On("CancelOrderByUuid", ctx, uuid)}
}

func (_c *OrderRepository_CancelOrderByUuid_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_CancelOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_CancelOrderByUuid_Call) Return(_a0 model.CancelResponse, _a1 error) *OrderRepository_CancelOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CancelOrderByUuid_Call) RunAndReturn(run func(context.Context, string) (model.CancelResponse, error)) *OrderRepository_CancelOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderRepository) CreateOrder(ctx context.Context, req *model.CreateOrderRequest) (string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) (string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) string); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateOrderRequest
func (_e *OrderRepository_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderRepository_CreateOrder_Call {
	return &OrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *OrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, req *model.CreateOrderRequest)) *OrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) Return(_a0 string, _a1 error) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.CreateOrderRequest) (string, error)) *OrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUuid provides a mock function with given fields: ctx, uuid
func (_m *OrderRepository) GetOrderByUuid(ctx context.Context, uuid string) (model.Order, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUuid")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUuid'
type OrderRepository_GetOrderByUuid_Call struct {
	*mock.Call
}

// GetOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderRepository_Expecter) GetOrderByUuid(ctx interface{}, uuid interface{}) *OrderRepository_GetOrderByUuid_Call {
	return &OrderRepository_GetOrderByUuid_Call{Call: _e.mock.On("GetOrderByUuid", ctx, uuid)}
}

func (_c *OrderRepository_GetOrderByUuid_Call) Run(run func(ctx context.Context, uuid string)) *OrderRepository_GetOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrderByUuid_Call) Return(_a0 model.Order, _a1 error) *OrderRepository_GetOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderByUuid_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *OrderRepository_GetOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// PayForOrderByUuid provides a mock function with given fields: ctx, request
func (_m *OrderRepository) PayForOrderByUuid(ctx context.Context, request *model.PaymentRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for PayForOrderByUuid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.PaymentRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_PayForOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayForOrderByUuid'
type OrderRepository_PayForOrderByUuid_Call struct {
	*mock.Call
}

// PayForOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - request *model.PaymentRequest
func (_e *OrderRepository_Expecter) PayForOrderByUuid(ctx interface{}, request interface{}) *OrderRepository_PayForOrderByUuid_Call {
	return &OrderRepository_PayForOrderByUuid_Call{Call: _e.mock.On("PayForOrderByUuid", ctx, request)}
}

func (_c *OrderRepository_PayForOrderByUuid_Call) Run(run func(ctx context.Context, request *model.PaymentRequest)) *OrderRepository_PayForOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.PaymentRequest))
	})
	return _c
}

func (_c *OrderRepository_PayForOrderByUuid_Call) Return(_a0 error) *OrderRepository_PayForOrderByUuid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_PayForOrderByUuid_Call) RunAndReturn(run func(context.Context, *model.PaymentRequest) error) *OrderRepository_PayForOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, uuid, update
func (_m *OrderRepository) UpdateOrder(ctx context.Context, uuid string, update model.OrderUpdate) error {
	ret := _m.Called(ctx, uuid, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderUpdate) error); ok {
		r0 = rf(ctx, uuid, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - update model.OrderUpdate
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, uuid interface{}, update interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, uuid, update)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, uuid string, update model.OrderUpdate)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderUpdate))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return(_a0 error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, string, model.OrderUpdate) error) *OrderRepository_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
