// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrderByUuid implements CancelOrderByUuid operation.
//
// Cancel order.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrderByUuid(ctx context.Context, params CancelOrderByUuidParams) (r CancelOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrder implements CreateOrder operation.
//
// Create order.
//
// POST /api/v1/orders/
func (UnimplementedHandler) CreateOrder(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderByUuid implements GetOrderByUuid operation.
//
// Get Order data.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetOrderByUuid(ctx context.Context, params GetOrderByUuidParams) (r GetOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PayForOrderByUuid implements PayForOrderByUuid operation.
//
// Order payment.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) PayForOrderByUuid(ctx context.Context, req *PayOrderRequest, params PayForOrderByUuidParams) (r PayForOrderByUuidRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
