// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"fmt"
)

func (s *GenericErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/bad_request_error
type BadRequestError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *BadRequestError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *BadRequestError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *BadRequestError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *BadRequestError) SetMessage(val string) {
	s.Message = val
}

func (*BadRequestError) cancelOrderByUuidRes() {}
func (*BadRequestError) createOrderRes()       {}
func (*BadRequestError) getOrderByUuidRes()    {}
func (*BadRequestError) payForOrderByUuidRes() {}

// Ref: #/components/schemas/conflict_error
type ConflictError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ConflictError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ConflictError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ConflictError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ConflictError) SetMessage(val string) {
	s.Message = val
}

func (*ConflictError) cancelOrderByUuidRes() {}
func (*ConflictError) payForOrderByUuidRes() {}

// Ref: #/components/schemas/create_order_request
type CreateOrderRequest struct {
	// UUID пользователя.
	UserUUID string `json:"user_uuid"`
	// Список запчастей для заказа.
	PartUuids []string `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []string {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []string) {
	s.PartUuids = val
}

// Ref: #/components/schemas/create_order_response
type CreateOrderResponse struct {
	// Уникальный UUID заказа.
	OrderUUID string `json:"order_uuid"`
	// Итоговая цена заказа.
	TotalPrice float32 `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() string {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float32 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

// Ref: #/components/schemas/generic_error
type GenericError struct {
	// HTTP-код ошибки.
	Code OptInt `json:"code"`
	// Описание ошибки.
	Message OptString `json:"message"`
}

// GetCode returns the value of Code.
func (s *GenericError) GetCode() OptInt {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *GenericError) GetMessage() OptString {
	return s.Message
}

// SetCode sets the value of Code.
func (s *GenericError) SetCode(val OptInt) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *GenericError) SetMessage(val OptString) {
	s.Message = val
}

// GenericErrorStatusCode wraps GenericError with StatusCode.
type GenericErrorStatusCode struct {
	StatusCode int
	Response   GenericError
}

// GetStatusCode returns the value of StatusCode.
func (s *GenericErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *GenericErrorStatusCode) GetResponse() GenericError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GenericErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *GenericErrorStatusCode) SetResponse(val GenericError) {
	s.Response = val
}

// Ref: #/components/schemas/internal_server_error
type InternalServerError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *InternalServerError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *InternalServerError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *InternalServerError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *InternalServerError) SetMessage(val string) {
	s.Message = val
}

func (*InternalServerError) cancelOrderByUuidRes() {}
func (*InternalServerError) createOrderRes()       {}
func (*InternalServerError) getOrderByUuidRes()    {}
func (*InternalServerError) payForOrderByUuidRes() {}

// Ref: #/components/schemas/no_content_response
type NoContentResponse struct {
	// HTTP-код ответа на отмену заказа.
	Code int `json:"code"`
	// Описание.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NoContentResponse) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NoContentResponse) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NoContentResponse) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NoContentResponse) SetMessage(val string) {
	s.Message = val
}

func (*NoContentResponse) cancelOrderByUuidRes() {}

// Ref: #/components/schemas/not_found_error
type NotFoundError struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *NotFoundError) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *NotFoundError) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *NotFoundError) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *NotFoundError) SetMessage(val string) {
	s.Message = val
}

func (*NotFoundError) cancelOrderByUuidRes() {}
func (*NotFoundError) createOrderRes()       {}
func (*NotFoundError) getOrderByUuidRes()    {}
func (*NotFoundError) payForOrderByUuidRes() {}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/order
type Order struct {
	// Уникальный идентификатор заказа.
	OrderUUID string `json:"order_uuid"`
	// Идентификатор пользователя, сделавшего заказ.
	UserUUID string `json:"user_uuid"`
	// Список UUID деталей, входящих в заказ.
	PartsUUID []string `json:"parts_uuid"`
	// Общая стоимость заказа.
	TotalPrice float32 `json:"total_price"`
	// UUID транзакции, если доступен.
	TransactionUUID OptNilString `json:"transaction_uuid"`
	// Метод платежа, если доступен.
	PaymentMethod OptNilString `json:"payment_method"`
	// Статус заказа (например, создан, оплачен, отменён).
	Status string `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *Order) GetOrderUUID() string {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Order) GetUserUUID() string {
	return s.UserUUID
}

// GetPartsUUID returns the value of PartsUUID.
func (s *Order) GetPartsUUID() []string {
	return s.PartsUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Order) GetTotalPrice() float32 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *Order) GetTransactionUUID() OptNilString {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *Order) GetPaymentMethod() OptNilString {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *Order) GetStatus() string {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *Order) SetOrderUUID(val string) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Order) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPartsUUID sets the value of PartsUUID.
func (s *Order) SetPartsUUID(val []string) {
	s.PartsUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Order) SetTotalPrice(val float32) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *Order) SetTransactionUUID(val OptNilString) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *Order) SetPaymentMethod(val OptNilString) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *Order) SetStatus(val string) {
	s.Status = val
}

func (*Order) getOrderByUuidRes() {}

// Ref: #/components/schemas/pay_order_request
type PayOrderRequest struct {
	// UUID пользователя.
	UserUUID string `json:"user_uuid"`
	// Способ оплаты.
	PaymentMethod string `json:"payment_method"`
}

// GetUserUUID returns the value of UserUUID.
func (s *PayOrderRequest) GetUserUUID() string {
	return s.UserUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() string {
	return s.PaymentMethod
}

// SetUserUUID sets the value of UserUUID.
func (s *PayOrderRequest) SetUserUUID(val string) {
	s.UserUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val string) {
	s.PaymentMethod = val
}

// Ref: #/components/schemas/pay_order_response
type PayOrderResponse struct {
	// Id транзакции.
	TransactionUUID OptString `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() OptString {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val OptString) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payForOrderByUuidRes() {}
