// Code generated for Tikhonov Nikita`s service
// © Tikhonov Nikita 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	context "golang.org/x/net/context"

	model "github.com/TikhonovNikita1996/Go-microservises-project/order/internal/model"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrderByUuid provides a mock function with given fields: ctx, uuid
func (_m *OrderService) CancelOrderByUuid(ctx context.Context, uuid string) (model.CancelResponse, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrderByUuid")
	}

	var r0 model.CancelResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.CancelResponse, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.CancelResponse); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.CancelResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CancelOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrderByUuid'
type OrderService_CancelOrderByUuid_Call struct {
	*mock.Call
}

// CancelOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderService_Expecter) CancelOrderByUuid(ctx interface{}, uuid interface{}) *OrderService_CancelOrderByUuid_Call {
	return &OrderService_CancelOrderByUuid_Call{Call: _e.mock.On("CancelOrderByUuid", ctx, uuid)}
}

func (_c *OrderService_CancelOrderByUuid_Call) Run(run func(ctx context.Context, uuid string)) *OrderService_CancelOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_CancelOrderByUuid_Call) Return(_a0 model.CancelResponse, _a1 error) *OrderService_CancelOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CancelOrderByUuid_Call) RunAndReturn(run func(context.Context, string) (model.CancelResponse, error)) *OrderService_CancelOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderService) CreateOrder(ctx context.Context, req *model.CreateOrderRequest) (model.CreateOrderResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 model.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) (model.CreateOrderResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateOrderRequest) model.CreateOrderResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(model.CreateOrderResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateOrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, req *model.CreateOrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 model.CreateOrderResponse, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, *model.CreateOrderRequest) (model.CreateOrderResponse, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByUuid provides a mock function with given fields: ctx, uuid
func (_m *OrderService) GetOrderByUuid(ctx context.Context, uuid string) (model.Order, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUuid")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUuid'
type OrderService_GetOrderByUuid_Call struct {
	*mock.Call
}

// GetOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *OrderService_Expecter) GetOrderByUuid(ctx interface{}, uuid interface{}) *OrderService_GetOrderByUuid_Call {
	return &OrderService_GetOrderByUuid_Call{Call: _e.mock.On("GetOrderByUuid", ctx, uuid)}
}

func (_c *OrderService_GetOrderByUuid_Call) Run(run func(ctx context.Context, uuid string)) *OrderService_GetOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderService_GetOrderByUuid_Call) Return(_a0 model.Order, _a1 error) *OrderService_GetOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrderByUuid_Call) RunAndReturn(run func(context.Context, string) (model.Order, error)) *OrderService_GetOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// PayForOrderByUuid provides a mock function with given fields: ctx, userUuid, paymentMethod, uuid
func (_m *OrderService) PayForOrderByUuid(ctx context.Context, userUuid string, paymentMethod string, uuid string) (string, error) {
	ret := _m.Called(ctx, userUuid, paymentMethod, uuid)

	if len(ret) == 0 {
		panic("no return value specified for PayForOrderByUuid")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return rf(ctx, userUuid, paymentMethod, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, userUuid, paymentMethod, uuid)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userUuid, paymentMethod, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayForOrderByUuid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayForOrderByUuid'
type OrderService_PayForOrderByUuid_Call struct {
	*mock.Call
}

// PayForOrderByUuid is a helper method to define mock.On call
//   - ctx context.Context
//   - userUuid string
//   - paymentMethod string
//   - uuid string
func (_e *OrderService_Expecter) PayForOrderByUuid(ctx interface{}, userUuid interface{}, paymentMethod interface{}, uuid interface{}) *OrderService_PayForOrderByUuid_Call {
	return &OrderService_PayForOrderByUuid_Call{Call: _e.mock.On("PayForOrderByUuid", ctx, userUuid, paymentMethod, uuid)}
}

func (_c *OrderService_PayForOrderByUuid_Call) Run(run func(ctx context.Context, userUuid string, paymentMethod string, uuid string)) *OrderService_PayForOrderByUuid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *OrderService_PayForOrderByUuid_Call) Return(_a0 string, _a1 error) *OrderService_PayForOrderByUuid_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_PayForOrderByUuid_Call) RunAndReturn(run func(context.Context, string, string, string) (string, error)) *OrderService_PayForOrderByUuid_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, uuid, update
func (_m *OrderService) UpdateOrder(ctx context.Context, uuid string, update model.OrderUpdate) error {
	ret := _m.Called(ctx, uuid, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.OrderUpdate) error); ok {
		r0 = rf(ctx, uuid, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderService_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderService_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - update model.OrderUpdate
func (_e *OrderService_Expecter) UpdateOrder(ctx interface{}, uuid interface{}, update interface{}) *OrderService_UpdateOrder_Call {
	return &OrderService_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, uuid, update)}
}

func (_c *OrderService_UpdateOrder_Call) Run(run func(ctx context.Context, uuid string, update model.OrderUpdate)) *OrderService_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.OrderUpdate))
	})
	return _c
}

func (_c *OrderService_UpdateOrder_Call) Return(_a0 error) *OrderService_UpdateOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderService_UpdateOrder_Call) RunAndReturn(run func(context.Context, string, model.OrderUpdate) error) *OrderService_UpdateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
